kind: Deployment
apiVersion: apps/v1beta1
metadata:
  labels:
    app: docs
    release: v0.0.1
    appVersion: v0.0.1
  name: docs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: ahmedwaleedmalik/vuepress-starter-kit:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "50Mi"
            cpu: "50m"